# Generated by Django 4.1.3 on 2023-01-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230102_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_see_users', 'Может просматривать пользователей')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
