# Generated by Django 4.1.3 on 2022-12-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_tracker_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('description', models.CharField(max_length=2000, verbose_name='Title')),
                ('started_at', models.DateField(auto_now=True, null=True, verbose_name='Start')),
                ('finished_at', models.DateField(auto_now=True, null=True, verbose_name='Finish')),
                ('tracker_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracker', to='webapp.tracker', verbose_name='Tracker')),
            ],
        ),
    ]
