# Generated by Django 4.1.3 on 2022-12-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateField(auto_now=True, default='2022-06-12', verbose_name='Finish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateField(auto_now=True, default='2022-06-12', verbose_name='Start'),
            preserve_default=False,
        ),
    ]
