# Generated by Django 4.1.3 on 2022-12-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_project_description_alter_project_finished_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tracker_fk',
        ),
        migrations.AddField(
            model_name='tracker',
            name='project_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project_fk', to='webapp.project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
