# Generated by Django 4.1.3 on 2022-12-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_project_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='project_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_fk', to='webapp.project', verbose_name='Project'),
        ),
    ]
