# Generated by Django 4.1.3 on 2022-12-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_project_finished_at_alter_project_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='project_fk',
        ),
        migrations.AddField(
            model_name='tracker',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='webapp.project', verbose_name='Project'),
        ),
    ]
