# Generated by Django 4.1.3 on 2022-12-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_tracker_project_fk_tracker_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='project',
        ),
        migrations.AddField(
            model_name='tracker',
            name='projects_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_fk', to='webapp.project', verbose_name='Project'),
        ),
    ]
