# Generated by Django 4.1.3 on 2022-12-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_tracker_projects_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
