# Generated by Django 4.1.3 on 2022-12-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_tracker_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Title'),
        ),
    ]
