# Generated by Django 4.1.3 on 2022-12-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_delete_user_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can add users', 'может добавить пользователей '), ('can delete users', 'может удалять пользователей ')]},
        ),
    ]
