# Generated by Django 4.1.3 on 2022-12-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_users', 'может добавить пользователей '), ('can_delete_users', 'может удалять пользователей ')]},
        ),
    ]
