# Generated by Django 4.1.3 on 2023-01-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
