# Generated by Django 4.1.3 on 2023-01-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='git',
            field=models.URLField(blank=True, null=True),
        ),
    ]
