# Generated by Django 4.1.3 on 2023-01-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_alter_profile_about_alter_profile_git'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
